services:

  ai-backend:
    environment:
      DEVICE: '${GPU_INTEL_IRIS_DEVICE:-iGPU}'
      OLLAMA_FLASH_ATTENTION: '${GPU_INTEL_IRIS_OLLAMA_FLASH_ATTENTION:-1}'
      OLLAMA_INTEL_GPU: true
      OLLAMA_MAX_LOADED_MODELS: '${GPU_INTEL_IRIS_OLLAMA_MAX_LOADED_MODELS:-1}'
      OLLAMA_NUM_CTX: '${GPU_INTEL_IRIS_OLLAMA_NUM_CTX:-2048}'
      OLLAMA_NUM_PARALLEL: '${GPU_INTEL_IRIS_OLLAMA_NUM_PARALLEL:-1}'
      ONEAPI_DEVICE_SELECTOR: "${GPU_INTEL_IRIS_OLLAMA_ONEAPI_DEVICE_SELECTOR:-'level_zero:0'}"
      ZES_ENABLE_SYSMAN: '${GPU_INTEL_IRIS_OLLAMA_ZES_ENABLE_SYSMAN:-1}'
    image: '${GPU_INTEL_IRIS_BACKEND_IMAGE:-docker.io/uberchuckie/ollama-intel-gpu:latest}'

  ai-frontend:
    environment:
      AUTOMATIC1111_CFG_SCALE: '${GPU_INTEL_IRIS_AUTOMATIC1111_CFG_SCALE:-1.0}'
      ENABLE_OPENAI_API: '${{GPU_INTEL_IRIS_FRONTEND_ENABLE_OPENAI_API:-False}}'
      IMAGE_GENERATION_MODEL: '${{GPU_INTEL_IRIS_FRONTEND_IMAGE_MODEL:-DreamShaper8_LCM.safetensors}}'
      IMAGE_SIZE: '${GPU_INTEL_IRIS_FRONTEND_IMAGE_SIZE:-512x512}'
      IMAGE_STEPS: '${GPU_INTEL_IRIS_FRONTEND_IMAGE_STEPS:-6}'

  ai-image:
    environment:
      ARGUMENT_LIST: |
        ${{ SDNEXT_ARGUMENT_LIST:-'--api --listen' }}
        ${{ GPU_INTEL_IRIS_SDNEXT_ARGUMENT_LIST:-'--lowvram --use-ipex' }}

  ai-model-image:
    environment:
      SDNEXT_MODEL_LIST: >-
        ${GPU_INTEL_IRIS_SDNEXT_MODEL_LIST:-"https://huggingface.co/Lykon/dreamshaper-8-lcm/resolve/main/DreamShaper8_LCM.safetensors"}
