services:

  ai-backend:
    ## We'll want to add the nVidia GPU framework to the deploy so the discrete GPU can be properly utilized by the AI
    ##frontend when running on a system with an nVidia GPU. The environment variables will be set to allow users to
    ## easily configure the image generation settings and enable the OpenAI API if desired.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - 'gpu'
    devices: []
    environment:
      CUDA_VISIBLE_DEVICES: '${GPU_NVIDIA_VISIBLE_DEVICES:-0}'
      DEVICE: '${GPU_NVIDIA_DEVICE:-NVIDIA}'
      OLLAMA_FLASH_ATTENTION: '${GPU_NVIDIA_OLLAMA_FLASH_ATTENTION:-1}'
      OLLAMA_INTEL_GPU: false
      OLLAMA_MAX_LOADED_MODELS: '${GPU_NVIDIA_OLLAMA_MAX_LOADED_MODELS:-3}'
      OLLAMA_NUM_CTX: '${GPU_NVIDIA_OLLAMA_NUM_CTX:-4096}'
      OLLAMA_NUM_PARALLEL: '${GPU_NVIDIA_OLLAMA_NUM_PARALLEL:-1}'
      ONEAPI_DEVICE_SELECTOR: "${GPU_NVIDIA_OLLAMA_ONEAPI_DEVICE_SELECTOR:-'level_zero:0'}"
      ZES_ENABLE_SYSMAN: '${GPU_NVIDIA_OLLAMA_ZES_ENABLE_SYSMAN:-1}'
    image: '${GPU_NVIDIA_BACKEND_IMAGE:-docker.io/ollama/ollama:latest}'

  ai-frontend:
    environment:
      AUTOMATIC1111_CFG_SCALE: '${GPU_NVIDIA_AUTOMATIC1111_CFG_SCALE:-2.0}'
      ENABLE_OPENAI_API: '${{GPU_NVIDIA_FRONTEND_ENABLE_OPENAI_API:-False}}'
      IMAGE_GENERATION_MODEL: '${{GPU_NVIDIA_FRONTEND_IMAGE_MODEL:-DreamShaperXL_Lightning-SFW.safetensors}}'
      IMAGE_SIZE: '${GPU_NVIDIA_FRONTEND_IMAGE_SIZE:-1024x1024}'
      IMAGE_STEPS: '${GPU_NVIDIA_FRONTEND_IMAGE_STEPS:-4}'

  ai-image:
    ## We'll want to add the nVidia GPU framework to the deploy so the discrete GPU can be properly utilized by the AI
    ##frontend when running on a system with an nVidia GPU. The environment variables will be set to allow users to
    ## easily configure the image generation settings and enable the OpenAI API if desired.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - 'gpu'
    devices: []
    environment:
      ARGUMENT_LIST: |
        ${{ SDNEXT_ARGUMENT_LIST:-'--api --listen' }}
        ${{ GPU_NVIDIA_SDNEXT_ARGUMENT_LIST:-'--use-cuda' }}
      CUDA_FORCE_ATTENTION_SLICE: 1
      CUDA_VISIBLE_DEVICES: '${GPU_NVIDIA_VISIBLE_DEVICES:-0}'
      IPEX_FORCE_ATTENTION_SLICE: 0
      IPEXRUN: False
    image: '${GPU_NVIDIA_IMAGE_IMAGE:-docker.io/vladmandic/sdnext-cuda:latest}'

  ai-model-image:
    environment:
      SDNEXT_MODEL_LIST: >-
        ${GPU_NVIDIA_SDNEXT_MODEL_LIST:-"https://huggingface.co/Lykon/dreamshaper-xl-lightning/resolve/main/DreamShaperXL_Lightning-SFW.safetensors"}
